<?php

$members = [

  [
    'id' => 0,
    'nom' => 'Dév',
    'password' => 'dev+2022%matt',
    'status' => 'all',
    'adresse' => '',
    'mail' => 'contact@matthieuperez.fr',
    'tel' => 695378162,
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'birth' => 1983,
    'inscription' => '01/01/2022',
  ],

  [
    'id' => 1,
    'nom' => 'Alain',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Montpellier',
    'birth' => 1973,
    'inscription' => '09/11/2022',
  ],

  [
    'id' => 2,
    'nom' => 'Aline',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 34,
    'ville' => 'Béziers',
    'birth' => 2001,
    'inscription' => '12/06/2022',
  ],

  [
    'id' => 3,
    'nom' => 'Amandine',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'birth' => 1988,
    'inscription' => '30/04/2022',
  ],

  [
    'id' => 4,
    'nom' => 'Colette',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 33,
    'ville' => 'Bordeaux',
    'birth' => 1965,
    'inscription' => '05/10/2022',
  ],

  [
    'id' => 5,
    'nom' => 'Donald',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Caissargues',
    'birth' => 1997,
    'inscription' => '01/09/2022',
  ],

  [
    'id' => 6,
    'nom' => 'Henri',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 75,
    'ville' => 'Paris',
    'birth' => 1974,
    'inscription' => '11/09/2022',
  ],

  [
    'id' => 7,
    'nom' => 'Jeanne',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 34,
    'ville' => 'Lodève',
    'birth' => 1999,
    'inscription' => '22/07/2022',
  ],

  [
    'id' => 8,
    'nom' => 'La fée des bois',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 38,
    'ville' => 'Saint-Marcelin-de-Cray',
    'birth' => 1980,
    'inscription' => '24/07/2022',
  ],

  [
    'id' => 9,
    'nom' => 'Marc',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Mèze',
    'birth' => 2005,
    'inscription' => '11/07/2022',
  ],

  [
    'id' => 10,
    'nom' => 'Marcel',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Montpellier',
    'birth' => 1955,
    'inscription' => '30/10/2022',
  ],

  [
    'id' => 11,
    'nom' => 'Marceline',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 34,
    'ville' => 'Aigne',
    'birth' => 1965,
    'inscription' => '29/08/2022',
  ],

  [
    'id' => 12,
    'nom' => 'Matthieu',
    'password' => '',
    'status' => 'gold',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'birth' => 1981,
    'inscription' => '03/07/2022',
  ],

  [
    'id' => 13,
    'nom' => 'Maxens',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 13,
    'ville' => 'Marseille',
    'birth' => 1988,
    'inscription' => '12/10/2022',
  ],

  [
    'id' => 14,
    'nom' => 'Maxime',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'birth' => 1991,
    'inscription' => '05/10/2022',
  ],

  [
    'id' => 15,
    'nom' => 'Nicolas',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'birth' => 1983,
    'inscription' => '14/06/2022',
  ],

  [
    'id' => 16,
    'nom' => 'Paul',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Montbazin',
    'birth' => 1993,
    'inscription' => '04/11/2022',
  ],

  [
    'id' => 17,
    'nom' => 'Pépé la figue',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Russan',
    'birth' => 1954,
    'inscription' => '17/05/2022',
  ],

  [
    'id' => 18,
    'nom' => 'Pipou',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Lunel',
    'birth' => 2015,
    'inscription' => '29/07/2022',
  ],

  [
    'id' => 19,
    'nom' => 'Quentin',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'birth' => 1994,
    'inscription' => '19/07/2022',
  ],

  [
    'id' => 20,
    'nom' => 'Raymonde',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 80,
    'ville' => 'Amiens',
    'birth' => 1950,
    'inscription' => '08/09/2022',
  ],

  [
    'id' => 21,
    'nom' => 'René',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Vézénobres',
    'birth' => 1973,
    'inscription' => '10/08/2022',
  ],

  [
    'id' => 22,
    'nom' => 'Richard',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Bezouce',
    'birth' => 1977,
    'inscription' => '22/10/2022',
  ],

  [
    'id' => 23,
    'nom' => 'Ricou',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Manduel',
    'birth' => 1979,
    'inscription' => '10/09/2022',
  ],

  [
    'id' => 24,
    'nom' => 'Roselyne',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 59,
    'ville' => 'Lille',
    'birth' => 1974,
    'inscription' => '25/09/2022',
  ],

  [
    'id' => 25,
    'nom' => 'Thomas',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'birth' => 1985,
    'inscription' => '15/08/2022',
  ],

  [
    'id' => 26,
    'nom' => 'Carl',
    'password' => 'ghff?9761',
    'status' => 'manager',
    'adresse' => '',
    'mail' => 'dasilvacarlos12345@gmail.com',
    'tel' => 768401601,
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Lunel',
    'birth' => 1965,
    'inscription' => '01/01/2022',
  ],

  [
    'id' => 27,
    'nom' => 'Visiteur 1',
    'password' => 'rnej?6540',
    'status' => 'abonné',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'inconnu',
    'dpt' => 34,
    'ville' => 'Montpellier',
    'birth' => 1980,
    'inscription' => '',
  ],

  [
    'id' => 28,
    'nom' => 'Visiteur 2',
    'password' => 'mifv?9299',
    'status' => 'abonné',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'inconnu',
    'dpt' => 34,
    'ville' => 'Montpellier',
    'birth' => 1970,
    'inscription' => '',
  ],

];
