<?php

$members = [

  [
    'id' => 1,
    'nom' => 'Dév',
    'password' => 'dev+2022%matt',
    'status' => 'all',
    'adresse' => '',
    'mail' => 'contact@matthieuperez.fr',
    'tel' => 695378162,
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'photo' => 'profile-pic b&w.png',
    'birth' => '10/01/1983',
    'inscription' => '01/01/2022',
  ],

  [
    'id' => 27,
    'nom' => 'Carl',
    'password' => 'ghff?9761',
    'status' => 'manager',
    'adresse' => '',
    'mail' => 'dasilvacarlos12345@gmail.com',
    'tel' => 768401601,
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Lunel',
    'photo' => 'Carl.jpg',
    'birth' => '02/06/1968',
    'inscription' => '01/01/2022',
  ],

  [
    'id' => 2,
    'nom' => 'Test',
    'password' => 'testClient',
    'status' => 'non abonné',
    'adresse' => '',
    'mail' => 'test@mail.com',
    'tel' => 610111213,
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Montpellier',
    'photo' => '',
    'birth' => '12/05/1973',
    'inscription' => '09/11/2022',
  ],

  [
    'id' => 3,
    'nom' => 'Aline',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 34,
    'ville' => 'Béziers',
    'photo' => '',
    'birth' => '17/02/2001',
    'inscription' => '12/06/2022',
  ],

  [
    'id' => 4,
    'nom' => 'Amandine',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'photo' => '',
    'birth' => '16/10/1988',
    'inscription' => '30/04/2022',
  ],

  [
    'id' => 5,
    'nom' => 'Colette',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 33,
    'ville' => 'Bordeaux',
    'photo' => '',
    'birth' => '13/07/1965',
    'inscription' => '05/10/2022',
  ],

  [
    'id' => 6,
    'nom' => 'Donald',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Caissargues',
    'photo' => '',
    'birth' => '04/12/1997',
    'inscription' => '01/09/2022',
  ],

  [
    'id' => 7,
    'nom' => 'Henri',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 75,
    'ville' => 'Paris',
    'photo' => '',
    'birth' => '10/11/1974',
    'inscription' => '11/09/2022',
  ],

  [
    'id' => 8,
    'nom' => 'Jeanne',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 34,
    'ville' => 'Lodève',
    'photo' => '',
    'birth' => '09/02/1999',
    'inscription' => '22/07/2022',
  ],

  [
    'id' => 9,
    'nom' => 'La fée des bois',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 38,
    'ville' => 'Saint-Marcelin-de-Cray',
    'photo' => '',
    'birth' => '17/06/1980',
    'inscription' => '24/07/2022',
  ],

  [
    'id' => 10,
    'nom' => 'Marc',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Mèze',
    'photo' => '',
    'birth' => '14/12/2005',
    'inscription' => '11/07/2022',
  ],

  [
    'id' => 11,
    'nom' => 'Marcel',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Montpellier',
    'photo' => '',
    'birth' => '19/06/1955',
    'inscription' => '30/10/2022',
  ],

  [
    'id' => 12,
    'nom' => 'Marceline',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 34,
    'ville' => 'Aigne',
    'photo' => '',
    'birth' => '21/09/1965',
    'inscription' => '29/08/2022',
  ],

  [
    'id' => 13,
    'nom' => 'Matthieu',
    'password' => 'xwai?7807',
    'status' => 'gold',
    'adresse' => '',
    'mail' => 'matthieu.perez30@gmail.com',
    'tel' => 686429807,
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'photo' => 'profile-pic (8).png',
    'birth' => '02/09/1981',
    'inscription' => '03/07/2022',
  ],

  [
    'id' => 14,
    'nom' => 'Maxens',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 13,
    'ville' => 'Marseille',
    'photo' => '',
    'birth' => '05/09/1988',
    'inscription' => '12/10/2022',
  ],

  [
    'id' => 15,
    'nom' => 'Maxime',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'photo' => '',
    'birth' => '11/05/1991',
    'inscription' => '05/10/2022',
  ],

  [
    'id' => 16,
    'nom' => 'Nicolas',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'photo' => '',
    'birth' => '14/07/1983',
    'inscription' => '14/06/2022',
  ],

  [
    'id' => 17,
    'nom' => 'Paul',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 34,
    'ville' => 'Montbazin',
    'photo' => '',
    'birth' => '02/12/1993',
    'inscription' => '04/11/2022',
  ],

  [
    'id' => 18,
    'nom' => 'Pépé la figue',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Russan',
    'photo' => '',
    'birth' => '12/09/1954',
    'inscription' => '17/05/2022',
  ],

  [
    'id' => 19,
    'nom' => 'Pipou',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Lunel',
    'photo' => '',
    'birth' => '28/02/2015',
    'inscription' => '29/07/2022',
  ],

  [
    'id' => 20,
    'nom' => 'Quentin',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'photo' => '',
    'birth' => '12/08/1994',
    'inscription' => '19/07/2022',
  ],

  [
    'id' => 21,
    'nom' => 'Raymonde',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 80,
    'ville' => 'Amiens',
    'photo' => '',
    'birth' => '10/05/1950',
    'inscription' => '08/09/2022',
  ],

  [
    'id' => 22,
    'nom' => 'René',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Vézénobres',
    'photo' => '',
    'birth' => '04/02/1973',
    'inscription' => '10/08/2022',
  ],

  [
    'id' => 23,
    'nom' => 'Richard',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Bezouce',
    'photo' => '',
    'birth' => '01/09/1977',
    'inscription' => '22/10/2022',
  ],

  [
    'id' => 24,
    'nom' => 'Ricou',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Manduel',
    'photo' => '',
    'birth' => '21/09/1979',
    'inscription' => '10/09/2022',
  ],

  [
    'id' => 25,
    'nom' => 'Roselyne',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'femme',
    'dpt' => 59,
    'ville' => 'Lille',
    'photo' => '',
    'birth' => '04/12/1974',
    'inscription' => '25/09/2022',
  ],

  [
    'id' => 26,
    'nom' => 'Thomas',
    'password' => '',
    'status' => '',
    'adresse' => '',
    'mail' => '',
    'tel' => '',
    'genre' => 'homme',
    'dpt' => 30,
    'ville' => 'Nîmes',
    'photo' => '',
    'birth' => '04/01/1985',
    'inscription' => '15/08/2022',
  ],

];
